.\" Copyright (C) 2023 by Jody Bruchon <jody@jodybruchon.com>
.TH "LIBJODYCODE" "7" "2023-07-05" "3.1" "libjodycode"
.SH NAME
libjodycode \- shared code used by several tools written by Jody Bruchon

.SH SYNOPSIS
.B #include <libjodycode.h>

.SS "Alarm API"
.nf
.BI "int jc_alarm_ring"
.BI "int jc_start_alarm(const unsigned int " seconds ", const int " repeat ")"
.BI "int jc_stop_alarm(void)"

.SS "Cacheinfo API"
.nf
.BI "void jc_get_proc_cacheinfo(struct jc_proc_cacheinfo *" pci ")"

.SS "Error API"
.nf
.BI "const char *jc_get_errname(int " errnum ")"
.BI "const char *jc_get_errdesc(int " errnum ")"
.BI "int jc_print_error(int " errnum ")"

.SS "jodyhash API"
.nf
.BI "int jc_block_hash(jodyhash_t *" data ", jodyhash_t *" hash ", const size_t " count ")"

.SS "OOM (out-of-memory) API"
.nf
.BI "void jc_oom(const char * const restrict " msg ")"
.BI "void jc_nullptr(const char * restrict " func ")"a

.SS "Paths API"
.nf
.BI "int jc_collapse_dotdot(char * const " path ")"
.BI "int jc_make_relative_link_name(const char * const " src ", const char * const " dest ", char *" rel_path ")"

.SS "Size Suffix API"
.nf
.BI "const struct jc_size_suffix jc_size_suffix[]"

.SS "Sort API"
.nf
.BI "int jc_numeric_sort(char * restrict " c1 ", char * restrict " c2 ", int " sort_direction ")"

.SS "String-to-epoch API"
.nf
.BI "time_t jc_strtoepoch(const char * const " datetime ")"

.SS "String API"
.nf
.BI "int jc_strncaseeq(const char *" s1 ", const char *" s2 ", size_t " len ")"
.BI "int jc_strcaseeq(const char *" s1 ", const char *" s2 ")"
.BI "int jc_strneq(const char *" s1 ", const char *" s2 ", size_t " len ")"
.BI "int jc_streq(const char *" s1 ", const char *" s2 ")"

.SS "Version API"
.nf
.BI "const char *jc_version"
.BI "const char *jc_verdate"
.BI "const int jc_api_version"
.BI "const int jc_api_featurelevel"
.BI "const int jc_jodyhash_version"
.BI "const unsigned char jc_api_versiontable[]"

.SS "Windows stat() API"
.nf
.BI "time_t jc_nttime_to_unixtime(const uint64_t * const restrict " timestamp ")"
.BI "time_t jc_unixtime_to_nttime(const uint64_t * const restrict " timestamp ")"
.BI "int jc_win_stat(const char * const " filename ", struct jc_winstat * const restrict " buf ")"

.SS "Windows Unicode API"
.nf
.BI "int jc_fwprint(FILE * const restrict " stream ", const char * const restrict " str ", const int " cr ")"
.BI "void jc_slash_convert(char *" path ")"
.BI "void jc_set_output_modes(unsigned int " modes ")"
.BI "int jc_widearg_to_argv(int " argc ", wchar_t **" wargv ", char **" argv ")"

.PP
.SH DESCRIPTION
libjodycode is a software code library containing code shared among several of
the programs written by Jody Bruchon such as imagepile, jdupes, winregfs, and
zeromerge. These shared pieces of code were copied between each program as
they were updated. As the number of programs increased and keeping these
pieces of code synced became more annoying, the decision was made to combine
all of them into a single reusable shared library.

.SH NOTES

libjodycode is created and maintained by Jody Bruchon <jody@jodybruchon.com>

Bug reports/feature requests: https://github.com/jbruchon/libjodycode/issues

If you find this software useful, please consider financially supporting
its development through the author's home page:

https://www.jodybruchon.com/

.SH LICENSE

MIT License

Copyright (c) 2014-2023 Jody Lee Bruchon <jody@jodybruchon.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
