.TH LIBJODYCODE 7
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
libjodycode \- shared code used by several tools written by Jody Bruchon
.SH SYNOPSIS
.B libjodycode
[
.I options
]
.I DIRECTORIES
\|.\|.\|.

.SH DESCRIPTION
libjodycode is a software code library containing code shared among several of
the programs written by Jody Bruchon such as imagepile, jdupes, winregfs, and
zeromerge. These shared pieces of code were copied between each program as
they were updated. As the number of programs increased and keeping these
pieces of code synced became more annoying, the decision was made to combine
all of them into a single reusable shared library.

.SH REPORTING BUGS

Bug reports/feature requests: https://github.com/jbruchon/libjodycode/issues

All other libjodycode inquiries: contact Jody Bruchon <jody@jodybruchon.com>

.SH SUPPORTING DEVELOPMENT

If you find this software useful, please consider financially supporting
its development through the author's home page:

https://www.jodybruchon.com/

.SH AUTHOR
libjodycode is created and maintained by Jody Bruchon <jody@jodybruchon.com>

.SH LICENSE

MIT License

Copyright (c) 2014-2023 Jody Lee Bruchon <jody@jodybruchon.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
